### ISSUE TITLE
Support for JupyterLab

### ISSUE THREAD

**Issue by VincentMatthys** [PayLead/PyLighter#1]
JupyterLab is not currently supported - the buttons doesn't work.

Steps to reproduce:
launch https://github.com/PayLead/PyLighter/blob/master/demo/Simple_usage.ipynb

**Comment by EtienneTurc** [comment]
Indeed, JupyterLab is not currently supported. Actually the buttons seem to work but the rendering is not working. 
I recommend you to use classic Jupyter Notebook for now, until I add support for JupyterLab.

**Comment by EtienneTurc** [comment]
The linked pr adds support for Jupyter Lab. Everything should work as expected. However, the loader does not correctly display, and a 2px space is added with every new chunk created. I am currently working on fixing those minor issues.
